name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # Tests-dev:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Tests unitaires 
  #       run: echo "Tests unitaires et integrations"
  
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan 
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: Python-flask-redis-projet
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}