name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # Tests-dev:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Tests unitaires 
  #       run: echo "Tests unitaires et integrations"
  
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan 
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  k6-test:
    name: Exécuter des tests de charge
    runs-on: ubuntu-latest
    steps:
      - name: Téléchargement du code
        uses: actions/checkout@v4
      - name: Exécution test k6 
        uses: grafana/k6-action@v0.3.1
        with:
          filename: my-load-test.js
          flags: --vus 50 --duration 10s
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}