# on:
#     schedule:
#       # Runs every day At 01:00.
#       - cron:  '0 1 * * *'
on: [push]

jobs:

    zap_base_scan:
      runs-on: ubuntu-latest
      name: Scan ZAP website
      steps:
        - name: ZAP base Scan
          uses: zaproxy/action-baseline@v0.3.0
          with:
            target: 'https://www.zaproxy.org/'
       
    zap_full_scan:
        runs-on: ubuntu-latest
        name: Scan the webapplication
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              ref: master
          - name: ZAP full Scan
            uses: zaproxy/action-full-scan@v0.9.0
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
              target: 'https://www.zaproxy.org/'
              rules_file_name: '.zap/rules.tsv'
              cmd_options: '-a'
